# Generated by Django 2.0.2 on 2018-02-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
