# Generated by Django 2.0.2 on 2018-02-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20180213_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='info',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
