# Generated by Django 2.0.2 on 2018-02-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tourney_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='info',
        ),
    ]
