# Generated by Django 2.0.2 on 2018-02-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_tourney_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='name',
        ),
    ]
