# Generated by Django 2.0.2 on 2018-02-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_tourney_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='game',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='info',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
